name: edutainment
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  random_color: ^1.0.5
  email_validator: ^2.0.1
  commons: ^0.7.8+3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.18.0
  flutter_datetime_picker: ^1.3.2
  percent_indicator: ^3.0.1
  provider: ^4.0.0
  lite_rolling_switch: ^0.1.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1
  cloud_firestore: ^0.14.0
  audioplayers: ^0.9.0
  sqflite: ^2.0.0+3
  path: any
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  charts_flutter: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/geometric shapes/2D shapes filled/
    - assets/geometric shapes/2D shapes non filled/
    - assets/geometric shapes/2D shapes for calculations/
    - assets/animals/images/
    - assets/animals/sounds/

  fonts:
    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-ExtraBold.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
